version: 2

submodules:
  include: all
  recursive: true

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - sed -r "s/(requires-python = .+)9(.*)/\112\2/g" pyproject.toml
      - pip install uv
      - cat pyproject.toml
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy
