version: 2

submodules:
  include: all
  recursive: true

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - sed -i 's/>=3.9/>=3.12/g' pyproject.toml
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy
