coverage:
  status:
    # main branch
    project:
      default:
        target: auto
        informational: true

    # PRs
    patch:
      default:
        target: auto
        informational: true

comment: false

github_checks:
  annotations: false

ignore:
  - ".github"
